### ISSUE TITLE
Not functional anymore?

### ISSUE THREAD

**Issue by rickbeeloo** [nconrad/mauve_viewer#12]
**This looks like an awesome tool!** 
I was still able to install it, at least get the result page, however I keep getting:

```
Uncaught TypeError: Cannot read property 'clientX' of undefined
    at SVGGElement.<anonymous> (mauve-viewer.js:1)
    at SVGGElement.<anonymous> (d3.v6.js:1985)
```
and `Uncaught TypeError: Cannot read property 'sourceEvent' of undefined` also does happen.

So it does not seem to be working anymore, at least the dynamic part :( or did I miss something?

**Comment by nconrad** [comment]
@rickbeeloo, thanks!  I think it needs some attention/maintenance.  Maybe I'll work on it some. 

Without doing some testing, that error may be an incompatibility with d3 v6?  

I'll try to look into supporting v6 and/or bundling with d3 modules.

**Comment by rickbeeloo** [comment]
@nconrad For my `index.html` I indeed used `<script src="https://d3js.org/d3.v6.js"></script>`, so v6, and indeed when I change it to `<script src="https://d3js.org/d3.v5.min.js"></script>` it works :) 
So that's awesome as most current viewers are either old-fashioned or too static, thanks for putting effort in making this!
Have a nice weekend!
